spring:
  application.name: gateway-server
  profiles.active: dev
  config.import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:7070}
  cloud:
    config:
      fail-fast: true
      request-connect-timeout: 20000
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20

