global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'gateway-server'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gatewayserver:8072','host.docker.internal:7072']
  - job_name: 'licensing-service'
    scrape_interval: 2m
    scrape_timeout: 1m
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['licensing-service:8081','host.docker.internal:7081']
  - job_name: 'organization-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['organization-service:8082','host.docker.internal:7082']
