version: "3.9"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ../keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: password
    restart: unless-stopped
    networks:
      backend:
        aliases:
          - "keycloak"

  vault:
    image: vault:1.12.2
    container_name: vault_dev
    restart: always
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: "vault server -dev"
    networks:
      backend:
        aliases:
          - "vault"

networks:
  backend:
    name: backend
    driver: bridge