apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki
  - name: PostgreSQL
  - name: Redis

datasources:
  - name: Prometheus
    id: 1
    uid: prometheus-vvw
    orgId: 1
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
    readOnly: false

  - name: Tempo
    id: 2
    uid: tempo-vvw
    orgId: 1
    type: tempo
    typeName: Tempo
    typeLogoUrl: public/app/plugins/datasource/tempo/img/tempo_logo.svg
    access: proxy
    url: http://tempo:3100
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus-vvw
      tracesToLogs:
        datasourceUid: loki-vvw
        filterBySpanID: false
        filterByTraceID: true
        lokiSearch: true
        mapTagNamesEnabled: true
        mappedTags:
          - key: service.name
            value: application
        spanEndTimeShift: 1h
        spanStartTimeShift: 1h
        tags:
          - instance
          - pod
          - namespace
          - hostname
    readOnly: false

  - name: Loki
    id: 3
    uid: loki-vvw
    orgId: 1
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: http://loki:3100
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo-vvw
          matcherRegex: "\\[.+,(.+?),"
          name: TraceID
          url: "${__value.raw}"
    readOnly: false

  - name: PostgreSQL
    id: 4
    uid: postgres-vvw
    orgId: 1
    type: postgres
    typeName: PostgreSQL
    typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
    access: proxy
    url: postgres:5432
    user: postgres
    database: postgres
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false

  - name: Redis
    id: 5
    uid: redis-vvw
    orgId: 1
    type: redis-datasource
    typeName: Redis
    typeLogoUrl: public/plugins/redis-datasource/img/logo.svg
    access: proxy
    url: redis:6379
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData: { }
    readOnly: false

