server.port: 7070

spring:
  application.name: config-server
  profiles.active: git, vault
  cloud:
    config:
      server:
        native.search-locations: classpath:/config
        git:
           uri: https://github.com/letMeStore/configs
           defaultLabel: main
#          username: letMeStore
           username: '{cipher}AQBzXErgL4IMI00l6vhfg3eytXLL2Gb2FxAm4Fl8FbXj8Ar3xEp2Rib3iBS8+Y2tHvyft+D0MuTwUCqNySN1p1VKfVx07k46jV8KqtrZh8lJm77VD8YHtuG+Qd3o95/HNQymlBvjw8FNr5DshNyrdyEd3q/l4FkHPoUAWpaYOZMv0ig7xfAi/1RAO+0pcwy579K7Y2PP2VV3+X0nbm2oB1jRkLHBInZKeQAM5OnRptGWzOrq96emWQVTMkzlalwy9S8xuRdW5ermk/GC9UEVBVbEXjOYm59ArXwRz7f2Tm+FiuuJpF6oAoZcrW+uNx69nX6VBvzQ8+TJtOBfB1dJMz1mpfTfWzm5KqD/Oftk0umB3vjPzQkYCjUZEdTqgyOOvfM='
           password: '{cipher}AQAvXBeccmY5DJWplOUZNI7GEO7TAR8hgCdOnXkLLIq+UVOxQ/xpSMLic/VTBwzbTXGnyBX+mdeohQlAqONiWOHFITbwe3/2QP6k+2Uef1kXEoN949ukNNlWNHvVrWTqAVekMqv3VfPXzESqY+xxk2v1SR1pBKkX3Af0mLuLQ2X7EVkwQp1OyvSfmvc9OABjMfpzjrVBjtyCwYdHWaRqz9fJ/+4KRc1tpKWgB1MKc5Jz3auE1kQ47m5EQ8IIrtWgoZ3AaPycp1iwcm7OzMbRORGRQeY6Vkdiez5tnSM77qQmZibrxS8itPkNm0+cyG8m3Dz1wLJWCMcGd7xqmeHy9iBchWKJ151aD6904ionkyzJf5jYceTQSEOcsqXa3918VEmzyiIM3xD33rScFOGy4Co7U0o/f/B+iC0H08xleUw/SQeQvqzGbo6lsNmXcXv0rT2KjVCp5Pjw/5mKB7w2HBWFIwRd5UTpqVg6QlN9KYOnfQ=='
           order: 2
        vault:
          port: 8200
          host: 127.0.0.1
          kv-version: 2
#         token: root
          token: '{cipher}AQCLrloQuj6AgJ+Acu1oFC9lMHmAaHc4792DPdYHhVKs2fQLwwBaL9XZm39JcOMBppox9t8cuSpmNo6PS3A7STpeeuN2dbUV/fEikGThBaknbDwetv7ECBmM6pB5BMPYdpQO3CRL8xHeeREGqfCeWVbVfTWQtBCJADQKqWcHz3K1h8WUbBTEM4LwtIEG0KJKOUmPiayPqoRwtJ+/VD3Qiu6TjfQk6EkqUbJwOrR8MMtSmGQ7dwetlMTg6jfs+BAyw0kcSeMVFuQmkiFm9+1/YLdnSuvL3MrjnpSBYqZg9vJ3MA/9oUC/+v+FrNKjzIC3nZ5tjFc9xa16wDb1SPrQTyC6YO/O+FX/UNkHSp5w1JW1hteUpLpFRrcimAnvo/8Qfx8='
          authentication: token
          backend: secret
          default-key: ""
          order: 1

logging:
  level:
    org.springframework.web.client: TRACE

management.endpoints.web.exposure.include: "*"

encrypt:
  keyStore:
    location: classpath:/key/server.jks
    password: letmein
    alias: mytestkey
    secret: letmein

